export const ENV_KEYS = {
    USERS_MICROSERVICE_PORT: 'USERS_MICROSERVICE_PORT',
    AUTH_MICROSERVICE_PORT: 'AUTH_MICROSERVICE_PORT',
    DATABASE_URL: 'DATABASE_URL',
    ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
    SESSION_TOKEN_SECRET: 'SESSION_TOKEN_SECRET',
    RESET_TOKEN_SECRET: 'RESET_TOKEN_SECRET',
};
