export const ENV_KEYS = {
    PROFILE_MICROSERVICE_PORT: 'PROFILE_MICROSERVICE_PORT',
    AUTH_MICROSERVICE_PORT: 'AUTH_MICROSERVICE_PORT',
    EMAIL_MICROSERVICE_PORT: 'EMAIL_MICROSERVICE_PORT',
    DEV_EMAIL: 'DEV_EMAIL',
    DEV_EMAIL_PASSWORD: 'DEV_EMAIL_PASSWORD',
    RESET_URL: 'RESET_URL',
    DATABASE_URL: 'DATABASE_URL',
    ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
    SESSION_TOKEN_SECRET: 'SESSION_TOKEN_SECRET',
    RESET_TOKEN_SECRET: 'RESET_TOKEN_SECRET',
};
