export const ENV_KEYS = {
    PROFILE_MICROSERVICE_PORT: 'PROFILE_MICROSERVICE_PORT',
    AUTH_MICROSERVICE_PORT: 'AUTH_MICROSERVICE_PORT',
    EMAIL_MICROSERVICE_PORT: 'EMAIL_MICROSERVICE_PORT',
    EMAIL_SENDER_KEY: 'EMAIL_SENDER_KEY',
    EMAIL_DOMAIN_ADDRESS: 'EMAIL_DOMAIN_ADDRESS',
    RESET_URL: 'RESET_URL',
    DATABASE_URL: 'DATABASE_URL',
    ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
    SESSION_TOKEN_SECRET: 'SESSION_TOKEN_SECRET',
    RESET_TOKEN_SECRET: 'RESET_TOKEN_SECRET',
    RABBITMQ_URL: 'RABBITMQ_URL',
};
