export const AUTH_PATTERNS = {
    VALIDATE_CREDENTIAL: 'auth.validate',
    FIND: 'auth.find',
    FIND_BY_EMAIL: 'auth.find-email',
    CREATE: 'auth.create',
    UPDATE: 'auth.update',
    DELETE: 'auth.delete',
    LOGOUT: 'token.logout',
    REFRESH: 'token.refresh',
    RESET: 'token.reset',
    GENERATE_TOKEN: 'token.generate',
    DELETE_TOKEN: 'token.delete',
    DELETE_USER_TOKENS: 'token.removeAll',
    VALIDATE_TOKEN: 'token.validate',
};
