export const AUTH_PATTERNS = {
    LOGIN: 'auth.login',
    FIND: 'auth.find',
    LOGOUT: 'token.logout',
    REFRESH: 'token.refresh',
    RESET: 'token.reset',
    GENERATE_TOKEN: 'token.generate',
    DELETE_TOKEN: 'token.delete',
    DELETE_ALL_TOKENS: 'token.removeAll',
    VALIDATE_TOKEN: 'token.validate',
    CREATE: 'auth.create',
    UPDATE: 'auth.update',
    DELETE: 'auth.delete',
    VALIDATE_CREDENTIAL: 'auth.validate-credential',
};
