export const AUTH_PATTERNS = {
    VALIDATE_CREDENTIAL: 'auth.validate',
    FIND: 'auth.find',
    CREATE: 'auth.create',
    UPDATE: 'auth.update',
    DELETE: 'auth.delete',
    REQUEST_RESET: 'auth.request-reset',
    RESET_PASSWORD: 'auth.reset-password',
    LOGOUT: 'token.logout',
    REFRESH: 'token.refresh',
    GENERATE_TOKEN: 'token.generate',
    DELETE_TOKEN: 'token.delete',
    DELETE_USER_TOKENS: 'token.removeAll',
    VALIDATE_TOKEN: 'token.validate',
};
